from .CommonElements import CommonElements
from .CommonElements import css
from .CommonElements import link_text
from .MainPage import MainPage
from .ProductPage import ProductPage
from .CataloguePage import CataloguePage
from .AdminLoginPage import AdminLoginPage
from .SearchPage import SearchPage
from .AdminPanelPage import AdminPanelPage